version: '3.1'

services:
    historydb:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password
            MONGO_INITDB_DATABASE: mediscreen-history
        ports:
            - "27017:27017"
        expose:
            - "27017"
        volumes:
            - mediscreen-db:/var/lib/mediscreen-history
        container_name: historydb
    mongo-express:
        image: mongo-express
        container_name: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: password
            ME_CONFIG_MONGODB_SERVER: historydb
volumes:
    mediscreen-db:

